### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Thangart** [raqet/raqet.github.io#1]
Love the package!

However some more information on the site would be helpful

The site doens't give any information about the raqet-dependencies that are needed in order to install the deb packages.

Also the screenshots instructions state that the web server can be reached trough localhost:5555 but in the default case the server is at 5556. The site should also be called by adding /gui to the path since the default page is blank.

**Comment by raqet** [comment]
Thanks for the feedback. Will look into it.
BTW. Feel free to fork and suggest changes.

**Comment by raqet** [comment]
I think the debian packages contain the dependencies, but I guess you would want them in the documentation as well.

**Comment by raqet** [comment]
@Thangart Please review change

**Comment by Thangart** [comment]
@raqet This clears it up ! :D
